export const resources = {
  en: {
    translation: {
      welcome_message: 'Start Learning with the help of professionals',
      hero_message:
        'Put your future first! Start learning structured and well-explained lessons that will help you pass your provisional exam easily and quickly.',
      start_now: 'Start Now',
      students: 'Students',
      lessons: 'Lessons',
      questions: 'Questions',

      test: 'Test',

      igazeti: 'books',
      testimonial_header: 'See what other clients say',

      // Pricing-related translations
      choosePlan: 'Choose a plan',
      plan_one_header: 'Six Exams Plan',
      plan_one_description: 'If you want to study in a short period',
      exam_only_option: 'Complete only five exams',
      limited_attempts: 'Only Six attempts',
      video_access: 'No video access',
      reading_permission: 'No reading permission',
      duration_three_days: '6 Exam',

      plan_two_header: 'Full Access Plan',
      plan_two_description: 'Study with full access',
      unlimited_exam: 'Take any exam you want',
      unlimited_reading: 'Read all exams',
      video_permission: 'Access to videos',
      reading_lessons: 'Study lessons',
      duration_nine_days: '10 days',

      plan_three_header: 'Premium Access Plan',
      plan_three_description: 'Complete access to everything',
      unlimited_exam_three: 'Unlimited exam attempts',
      unlimited_reading_three: 'Unlimited reading',
      video_permission_three: 'Unlimited video access',
      reading_lessons_three: 'Unlimited lesson access',
      duration_fifteen_days: '15 days',

      plan_four_header: 'Premium Access Plan',
      plan_four_description: 'Complete access to everything',
      unlimited_exam_four: 'Unlimited exam attempts',
      unlimited_reading_four: 'Unlimited reading',
      video_permission_four: 'Unlimited video access',
      reading_lessons_four: 'Unlimited lesson access',
      duration_thirty_days: '30 days',

      call_to_action: 'Get started now',

      home: 'Home',
      exams: 'Exam',
      login: 'Login',
      pricing: 'Pricing',
      contact: 'Contact',

      contact_header: 'Contact Us or Call Us',
      contact_message: 'Send us a message or call us at our numbers.',
      phone_number: 'Your Phone Number',
      phone_placeholder: 'Enter your phone number',
      message_label: 'Your Message',
      message_placeholder: 'Write your message here',
      submit_button: 'Send Message',
      contact_info: 'Or call us at:',
      contact_number: '+250 787 787 878',
      request_reset: 'Request code',
      verify: 'Verify Code',
      reset_password: 'Confirm Reset Password',

      alt: {
        logo: 'Umuhanda Logo',
        auth_image: 'Auth Illustration',
      },
      signin: {
        title: 'Sign In',
        phone_label: 'Email Or Phone Number',
        phone_placeholder: 'Enter your email or phone number',
        password_label: 'Password',
        password_placeholder: 'Enter your password',
        login: 'Sign In',
        forgot_password: 'Forgot Password?',
        create_account: 'Create Account',
      },

      signup: 'Create an Account',
      fullName: 'Your Full Name',
      enterFullName: 'Enter your full name',
      email: 'Email',
      enterEmail: 'Enter your email (if you have it)',
      phoneNumber: 'Phone Number',
      enterPhoneNumber: 'Enter your phone number',
      password: 'Password',
      enterPassword: 'Enter your password',
      confirmPassword: 'Confirm-Password',
      enterConfirmPassword: 'Re-Type your password',
      signUp: 'Sign Up',
      backToSignIn: 'Back to Sign In',
      phone_email_label: 'Email Or Phone Number',
      phone_email_placeholder: 'Enter your email or phone number',

      resetPassword: 'Reset Password',
      enter_reset_code: 'Enter Reset Code',
      submit: 'Submit',
      createAccount: 'Create an Account',

      exams_taken: 'Exams Taken',
      highest_score: 'Highest Score',
      attempts_left: 'Exam Attempts Left',

      exam_title: 'Exam Instructions',
      question_count: 'Number of Questions',
      time_limit: 'Time Limit',
      total_score: 'Total Score',
      passing_score: 'Passing Score',
      start_exam: 'Start Exam',

      welcome: 'Welcome',
      profile_title: 'Update Profile',
      profile_desc: 'Enter the required information to complete your profile.',
      name_label: 'Your Name',
      birthdate_label: 'Date of Birth',
      country_label: 'Country',
      password_label: 'Password',
      email_label: 'Email',
      phone_number_label: 'Phone Number',
      address_label: 'Your Address',
      city_label: 'City',
      change_password: 'Change Password',
      current_password: 'Current Password',
      new_password: 'New Password',
      confirm_new_password: 'Confirm New Password',

      settings: 'Settings',
      logout: 'Logout',
      needToPayGazette: 'You need to pay Rwf 2000 to be allowed to download Gazette',
      needToPayGazetteButton: 'Pay Rwf 2000 to continue',
      payButton: 'Pay now',
      chooseSubLanguage: 'Choose Language',
      chooseSubPlan: 'Choose Plan',

      courses: 'Courses',
      no_attempts: 'No More Exam Attempts Left! 🚀',
      upgrade_message:
        'Upgrade your subscription to get unlimited access to practice exams and improve your knowledge!',
      upgrade_button: 'Upgrade Now',
      no_sub: "You don't have Subscription! 🚀",
      upgrade_sub_message: 'Please buy subscription to get access/read to gazette!',
      updadate_password: 'Change Password',
      update_profile_button: 'Update Profile',
      payment_success_body:
        'Thank you for subscribing. You can now start learning or taking your trial exams.',
      payment_success_title: 'Payment Successful!',
      payment_failure_body: 'Unfortunately, your payment could not be processed.',
      payment_failure_body2: 'Your invoice is still valid for 15 minutes.',
      payment_failure_title: 'Payment Failed !',
      payment_response_button: 'Ok',
      payment_retry_button: 'Rety Payment',
      payment_change_plan: 'Choose a different plan',
      language_mismatch_title: 'Language Mismatch',
      language_mismatch_body:
        "Your subscription doesn't support this language. Please use the one you subscribed for or buy another Subscription.",
      language_mismatch_close: 'Got it !',
      no_subs: 'No subscriptions available',
      back_to_dashboard: 'Dashboard',
      buy_new: 'Buy new',
      back_home: 'Back Home',
    },
  },
  fr: {
    translation: {
      welcome_message: 'Bienvenue à React et react-i18next',
      hero_message:
        'Mettez votre avenir en premier ! Commencez à apprendre des leçons structurées et bien expliquées qui vous aideront à réussir votre examen provisoire facilement et rapidement.',
      start_now: 'Commencez Maintenant',
      students: 'Étudiants',
      lessons: 'Leçons',
      questions: 'Questions',

      test: 'Test',

      igazeti: 'Livre',
      testimonial_header: 'Découvrez ce que disent les autres clients',

      // Pricing-related translations
      choosePlan: 'Choisissez un plan',
      plan_one_header: 'Plan six Examens',
      plan_one_description: 'Si vous voulez étudier en peu de temps',
      exam_only_option: 'Complétez seulement cinq examens',
      limited_attempts: 'Seulement cinq tentatives',
      video_access: "Pas d'accès aux vidéos",
      reading_permission: "Pas d'autorisation de lecture",
      duration_three_days: '6 Examens',

      plan_two_header: 'Plan Accès Complet',
      plan_two_description: 'Étudier avec un accès complet',
      unlimited_exam: 'Faites tous les examens que vous voulez',
      unlimited_reading: 'Lire tous les examens',
      video_permission: 'Accès aux vidéos',
      reading_lessons: 'Étudier les leçons',
      duration_nine_days: '10 jours',

      plan_three_header: 'Plan Accès Premium',
      plan_three_description: 'Accès complet à tout',
      unlimited_exam_three: "Tentatives d'examen illimitées",
      unlimited_reading_three: 'Lecture illimitée',
      video_permission_three: 'Accès illimité aux vidéos',
      reading_lessons_three: 'Accès illimité aux leçons',
      duration_fifteen_days: '15 jours',

      plan_four_header: 'Plan Accès Premium',
      plan_four_description: 'Accès complet à tout',
      unlimited_exam_four: "Tentatives d'examen illimitées",
      unlimited_reading_four: 'Lecture illimitée',
      video_permission_four: 'Accès illimité aux vidéos',
      reading_lessons_four: 'Accès illimité aux leçons',
      duration_thirty_days: '30 jours',

      call_to_action: 'Commenzez',

      home: 'Accueil',
      exams: 'Passer les examens',
      login: 'Se connecter',
      pricing: 'Tarification',
      contact: 'Contactez-nous',

      contact_header: 'Contactez-nous ou appelez-nous',
      contact_message: 'Envoyez-nous un message ou appelez-nous à nos numéros.',
      phone_number: 'Votre numéro de téléphone',
      phone_placeholder: 'Entrez votre numéro de téléphone',
      message_label: 'Votre message',
      message_placeholder: 'Écrivez votre message ici',
      submit_button: 'Envoyer le message',
      contact_info: 'Ou appelez-nous à :',
      contact_number: '+250 787 787 878',
      request_reset: 'Demande Code',
      verify: 'vérifier un code',
      reset_password: 'Confirmer la réinitialisation du mot de passe',

      alt: {
        logo: 'Logo Umuhanda',
        auth_image: "Illustration d'authentification",
      },
      signin: {
        title: 'Se Connecter',
        phone_label: 'Email Ou Numéro de Téléphone',
        phone_placeholder: 'Entrez votre email ou numéro de téléphone',
        password_label: 'Mot de Passe',
        password_placeholder: 'Entrez votre mot de passe',
        login: 'Connexion',
        forgot_password: 'Mot de passe oublié ?',
        create_account: 'Créer un Compte',
      },

      signup: 'Créer un Compte',
      fullName: 'Votre Nom Complet',
      enterFullName: 'Entrez votre nom complet',
      email: 'Votre Email',
      enterEmail: "Entrez votre email (si vous l'avez)",
      phoneNumber: 'Numéro de Téléphone',
      enterPhoneNumber: 'Entrez votre numéro de téléphone',
      password: 'Mot de Passe',
      enterPassword: 'Entrez votre mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      enterConfirmPassword: 'Ressaisissez votre mot de passe',
      signUp: "S'inscrire",
      backToSignIn: 'Retour à la Connexion',
      phone_email_label: 'Email Ou Numéro de Téléphone',
      phone_email_placeholder: 'Entrez votre email ou numéro de téléphone',

      resetPassword: 'Réinitialiser le Mot de Passe',
      enter_reset_code: 'Entrez le code de réinitialisation',
      submit: 'Soumettre',
      createAccount: 'Créer un Compte',

      exams_taken: "Nombre de fois où vous avez passé l'examen",
      highest_score: 'Score le plus élevé',
      attempts_left: "Tentatives d'examen restantes",

      exam_title: "Instructions de l'examen",
      question_count: 'Nombre de questions',
      time_limit: 'Limite de temps',
      total_score: 'Score total',
      passing_score: 'Score de réussite',
      start_exam: "Commencer l'examen",
      welcome: 'Bienvenue',
      profile_title: 'Mettre à jour le profil',
      profile_desc: 'Entrez les informations requises pour compléter votre profil.',
      name_label: 'Votre nom',
      birthdate_label: 'Date de naissance',
      country_label: 'Pays',
      password_label: 'Mot de passe',
      email_label: 'Email',
      phone_number_label: 'Numéro de téléphone',
      address_label: 'Votre adresse',
      city_label: 'Ville',
      change_password: 'Modifier le mot de passe',
      current_password: 'Mot de passe actuel',
      new_password: 'Nouveau mot de passe',
      confirm_new_password: 'Confirmer le Nouveau mot de passe',
      settings: 'Paramètres',
      logout: 'Déconnexion',
      needToPayGazette: 'Vous devez payer 2000 Rwf pour pouvoir télécharger Gazette',
      needToPayGazetteButton: 'Payez 2000 Rwf pour continuer',
      payButton: 'Payer maintenant',
      chooseSubLanguage: 'Choisir la Langue',
      chooseSubPlan: 'Choisir un plan',

      courses: 'Cours',
      no_attempts: "Plus de tentatives d'examen disponibles ! 🚀",
      upgrade_message:
        'Mettez à niveau votre abonnement pour un accès illimité aux examens pratiques et améliorez vos connaissances !',
      upgrade_button: 'Mettre à niveau maintenant',
      no_sub: "Vous n'avez pas d'abonnement !🚀",
      upgrade_sub_message: 'Veuillez acheter un abonnement pour avoir accès/lire la gazette !',
      updadate_password: 'Changer le mot de passe',
      update_profile_button: 'Mettre à jour le profil',
      payment_success_body:
        "Merci de votre inscription. Vous pouvez désormais commencer à apprendre ou à passer vos examens d'essai.!",
      payment_failure_body: "Malheureusement, votre paiement n'a pas pu être traité.",
      payment_failure_body2: 'Votre facture est encore valable 15 minutes.',
      payment_failure_title: 'Échec du paiement!',
      payment_response_button: 'Oui',
      payment_retry_button: 'Paiement de remboursement',
      payment_change_plan: 'Choisissez un autre forfait',
      language_mismatch_title: 'Incompatibilité linguistique',
      language_mismatch_body:
        'Votre abonnement ne prend pas en charge cette langue. Veuillez utiliser celle que vous avez choisie ou souscrire un autre abonnement.',
      language_mismatch_close: "J'ai compris !",
      no_subs: 'Aucun abonnement disponible',
      back_to_dashboard: 'Tableau de bord ',
      buy_new: 'Acheter du neuf',
      back_home: "Retour à la page d'accueil",
    },
  },
  kiny: {
    translation: {
      welcome_message: 'Gutsinda Provisoire Biroroshye Hamwe natwe!',
      hero_message:
        'Shyira imbere ejo heza hawe! Tangira kwiga amasomo arambuye kandi asobanutse azagufasha gutsinda kizamini cyawe cya provisoire mu buryo bworoshye kandi bwihuse.',
      start_now: 'Tangira Nonaha',
      students: 'Abanyeshuri',
      lessons: 'Amasomo',
      questions: 'Ibibazo',

      test: 'Isuzume',

      igazeti: 'Igazeti',
      testimonial_header: 'Reba ibyo abandi banyeshuri bavuga',

      // Pricing-related translations
      choosePlan: 'Hitamo Ifatabuguzi',
      plan_one_header: "Plan y'Ibizamini Bitandatu",
      plan_one_description: 'Niba ushaka kwiga mugihe gitoya',
      exam_only_option: 'Gukora ibizamini bitanu gusa',
      limited_attempts: 'Inshuro 6 gusa',
      video_access: 'Nta video wemerewe kureba',
      reading_permission: 'Nta gusoma wemerewe',
      duration_three_days: 'Ibizamini bitanu',

      plan_two_header: "Plan y'Ubwisungane Bwohejuru",
      plan_two_description: 'Kwiga ufite uburenganzira bwose',
      unlimited_exam: 'Gukora ibizamini byose ushaka',
      unlimited_reading: 'Gusoma ibizamini byose',
      video_permission: 'Kureba amashusho',
      reading_lessons: 'Gusoma amasomo',
      duration_nine_days: '9 iminsi',

      plan_three_header: "Plan y'Ubwisungane Bwohejuru",
      plan_three_description: 'Kwiga ufite uburenganzira bwose ku byose',
      unlimited_exam_three: 'Gukora ibizamini byose ushaka',
      unlimited_reading_three: 'Gusoma ibizamini byose',
      video_permission_three: 'Kureba amashusho byose',
      reading_lessons_three: 'Gusoma amasomo yose',
      duration_fifteen_days: '15 iminsi',

      plan_four_header: "Plan y'Ubwisungane Bwohejuru",
      plan_four_description: 'Kwiga ufite uburenganzira bwose ku byose',
      unlimited_exam_four: 'Gukora ibizamini byose ushaka',
      unlimited_reading_four: 'Gusoma ibizamini byose',
      video_permission_four: 'Kureba amashusho byose',
      reading_lessons_four: 'Gusoma amasomo yose',
      duration_thirty_days: '30 iminsi',

      call_to_action: ' Witegure gukora ikizamini mugihe gito',

      home: 'Ahabanza',
      exams: 'Kora Ibizamini',
      login: 'Injiramo',
      pricing: 'Ibiciro',
      contact: 'Twandikire',

      contact_header: 'Twandikire cyangwa uduhamagare',
      contact_message: 'Twohereze ubutumwa cyangwa duhamagare kuri nimero zacu.',
      phone_number: 'Nimero yawe ya telephone',
      phone_placeholder: 'Andika nimero yawe ya telephone',
      message_label: 'Ubutumwa bwawe',
      message_placeholder: 'Andika ubutumwa hano',
      submit_button: 'Ohereza Ubutumwa',
      contact_info: 'Cyangwa uduhamagare kuri:',
      contact_number: '+250 787 787 878',
      request_reset: 'Saba kode',
      verify: 'Suzuma kode',
      reset_password: 'Emeza guhindura ijambo banga',
      enter_reset_code: 'Injiza kode yo guhindura ijambo banga',

      alt: {
        logo: 'Ikirangantego cya Umuhanda',
        auth_image: "Ishusho y'iyinjira",
      },
      signin: {
        title: 'Injiramo',
        phone_label: 'Imeli cg Nimero ya Telephone',
        phone_placeholder: 'Injiza imeli cg nimero yawe',
        password_label: "Umubare w'Ibanga",
        password_placeholder: "Injiza umubare w'ibanga",
        login: 'Injiramo',
        forgot_password: "Wibagiwe W'Ibanga?",
        create_account: 'Kora Konti',
      },

      signup: 'Kora Konte',
      fullName: 'Amazina yawe',
      enterFullName: 'Andika amazina yawe',
      email: 'Imeli yawe',
      enterEmail: 'Andika Imeli yawe (Niba uyifite)',
      phoneNumber: 'Nimero ya Telephone',
      enterPhoneNumber: 'Injiza nimero yawe',
      password: "Umubare w'Ibanga",
      enterPassword: "Injiza umubare w'ibanga",
      confirmPassword: "Emeza Umubare w'Ibanga",
      enterConfirmPassword: "Ongera winjize umubare w'ibanga",
      signUp: 'Injiramo',
      backToSignIn: 'Subira Aho Winjirira',

      phone_email_label: 'Imeli cg nimero ya telefone',
      phone_email_placeholder: 'Injiza imeli yawe cg nimero ya telefone',
      resetPassword: 'Guhindura Ijambo banga',
      submit: 'Emeza',
      createAccount: 'Kora Konti',

      exams_taken: 'Inshuro wakoze ibizamini',
      highest_score: 'Amanota menshi wagize',
      attempts_left: 'Inshuro usigaje gukora ikizamini',

      exam_title: "Amabwiriza y'ikizamini",
      question_count: "Umubare w'ibibazo",
      time_limit: "Iminota y'ikizamini",
      total_score: 'Amanota yose',
      passing_score: 'Amanota yo gutsindiraho',
      start_exam: 'Tangira Ikizamini',

      profile_title: 'Hindura Profile',
      welcome: 'Murakaza Neza',
      profile_desc: 'Injiza amakuru akenewe kugira ngo uzuze profile yawe neza.',
      name_label: 'Amazina Yawe',
      birthdate_label: "Amatariki y' ivuko",
      country_label: 'Igihugu',
      password_label: "Umubare w' ibanga",
      email_label: 'Imeli',
      phone_number_label: 'Nimero ya telefone',
      address_label: 'Aho utuye',
      change_password: 'Hindura Ijambo Banga',
      current_password: 'Ijambo banga usanganywe',
      new_password: 'Ijambo banga rishya',
      confirm_new_password: 'Emeza ijambo banga rishya',
      city_label: 'Umugi',

      settings: 'Igenamiterere',
      logout: 'Gusohoka',
      needToPayGazette:
        'Mukeneye Kubanza Kwishyura Rwf 2000 Kugira ngo mwemererwe kumanura iyi Gazeti',
      needToPayGazetteButton: 'Ishyura Rwf 2000 ukomeze',
      payButton: 'Ishyura Nonaha',
      chooseSubLanguage: 'Hitamo Ururimi',
      chooseSubPlan: 'Hitamo Gahunda',

      courses: 'Amasomo',
      no_attempts: 'Nta mahirwe usigaranye yo gukora ikizamini! 🚀',
      upgrade_message:
        'Ongera ifatabuguzi ryawe kugirango ubone amahirwe adafite umubare w’ibizamini byo kwimenyereza no kongera ubumenyi bwawe!',
      upgrade_button: 'Ongera Ifatabuguzi nonaha',
      no_sub: 'Nta fatabuguzi mufite! 🚀',
      upgrade_sub_message: 'Gura ifatabuguzi ryawe kugirango ubone amahirwe yo gusoma igazeti!',
      update_password: 'Hindura Ijambo banga',
      update_profile_button: 'Hindura Imyirondoro',
      payment_success_body:
        'Murakoze kugura ifatabuguzi. Ubu mwatangira kwiga no gukora igerageza.',
      payment_success_title: 'Kwishyura Byagenze neza!',
      payment_failure_body: "Kubw'amahirwe make kwishyura kwanyu ntibibashije gukorwa.",
      payment_failure_body2: 'Inyemeza bwishyu yanyu iracyafite agaciro iminota 15.',
      payment_failure_title: 'Kwishyura ntibibashije gukunda !',
      payment_response_button: 'Yego',
      payment_retry_button: 'Gerageza kongera kwishyura',
      payment_change_plan: 'Hitabo irindi fatabuguzi',
      language_mismatch_title: 'Indimi ntizihuye',
      language_mismatch_body:
        'Ifatabuguzi ryawe ntago ryemera uru rurimi. Guma mu rurimi wafashemo ifatabuguzi ryawe cyangwa ugure irindi fatabuguzi.',
      language_mismatch_close: 'Yego',
      no_subs: 'Nta fatabuguzi mufite',
      back_to_dashboard: 'Aho Nigira ',
      buy_new: 'Gura rishya',
      back_home: 'Subira ahabanza',
    },
  },
};
