name: 🚀 Deploy React App to Hostinger via FTP

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build Vite App
        run: npm run build
        env:
          VITE_API_URL: https://backend-mpeh.onrender.com


      - name: 📤 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.umuhanda.org
          username: u568627481.github
          password: Umuhanda@123
          protocol: ftp      
          port: 21            
          local-dir: dist/
          server-dir: /
